### ISSUE TITLE
RFE: Support "and" matching for terms

### ISSUE THREAD

**Issue by jamesmanning** [Trellmor/BerryMotesGallery#2]
Searching for 2 terms appears to do a logical or operation, so looking for "luna sad" (without quotes) includes all luna and all sad emotes.

The Google approach would be "luna sad" being an implicit and operator then "luna OR sad" being a way of supporting logical or.

**Comment by Trellmor** [comment]
Emote names are now matched with AND instead of OR if multiple names are entered. Subreddits are matched with OR. I didn't implement the optional OR matching for names.

**Comment by jamesmanning** [comment]
@Trellmor thank you! You rock!
